############################
######## Libraries #########
############################

library(shiny)
library(ggplot2)
library(dplyr)
library(RColorBrewer)
library(ggpubr)
library(plotly)
library(ggrepel)
library(kohonen)
library(effectsize)
library(tibble)
library(tidyr)
library(rMQanalysis)
library(shinyBS)
library(DT)
library(mailtoR)
library(viridis)
set.seed(666)

############################
####### Variables ##########
############################

load("./InputFiles/01_LInfantum_Data.RData")
load("./InputFiles/02_LMajor_Data.RData")
load("./InputFiles/03_LMexicana_Data.RData")
load("./InputFiles/04_Orthology_Data.RData")

############################
######### Script ###########
############################

ui <-  navbarPage(title = HTML("<b>LInfDB</b>: <i><u>L</u>eishmania</i> <u>I</u>nfectome <u>D</u>ata <u>B</u>ase"),
                  theme = shinytheme("lumen"),
                  windowTitle = "Leishmania Infectome",
                  tabPanel("Welcome",
                           fluidRow(column(12,
                                           h2("Abstract"),
                                           p("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore 
                                             magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                                             consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
                                             Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. 
                                             Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore 
                                             magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo 
                                             consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. 
                                             Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                                             Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore 
                                             magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                                             consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
                                             Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."))),
                           fluidRow(column(12,
                                           h3("Experimental design"))),
                           fluidRow(column(2,
                                           br()),
                                    column(8,
                                           br(),
                                           img(src = "Image_01.png",  height = "100%", width = "100%"),
                                           br(),
                                           br(),
                                           br(),
                                           HTML("<b>Quantified proteins using mass spectrometry show dynamic expression throughout the infection.</b>
                                               (A) 3 Leishmania species were used to infect BMDMs in quadruplets. Whole cell lysates of 7 different time points
                                               were sent to mass spectrometry to quantify protein levels. (B) Total number of proteins quantified with 2 imputed
                                               values shows 2000 quantified mouse proteins, 1500 <i>L. mexicana</i> proteins, 1400 <i>L. major proteins</i>, and 
                                               1200 <i>L. infantum</i> proteins.")),
                                    column(2,
                                           br())),
                           fluidRow(column(12,
                                           tags$hr(style="border-color: darkgrey;"))),
                           fluidRow(column(12,
                                           strong("Quantitative MS analysis of infected macrophages identifies novel virulence factors in three different Leishmania species"),
                                           br(),
                                           br(),
                                           p("Nicolas Hagedorn",tags$sup("1"),",",
                                             "Albert Fradera-Sola",tags$sup("2"),",",
                                             "Melina Mitnacht",tags$sup("1"),",",
                                             "Tobias Gold",tags$sup("3"),",",
                                             "Ulrike Schleicher",tags$sup("3"),",",
                                             "Falk Butter",tags$sup("2"),
                                             "Christian J. Janzen",tags$sup("1"), 
                                             style = "font-size:10pt;"),
                                           em("# Indicates correspondance,
                                           1 Department of Cell & Developmental Biology, Biocenter, University of Würzburg, Würzburg, 97074, Germany
                                           2 Institute of Molecular Virology and Cell Biology, Freidrich-Loeffler-Institute, Greifswald, 17493, Germany
                                           3 Microbiology Institute-Clinical Microbiology, Immunology and Hygiene, University Hospital Erlangen and Friedrich-Alexander-University, Erlangen, 91054, Germany
                                              ",
                                              style = "font-size:9pt;"),
                                           br(),
                                           br(),
                                           p("App created by Albert Fradera-Sola in December 2021", style = "font-size:10pt;"),
                                           p("Comments and bug reports to the following e-mail: ", mailtoR(email = "A.FraderaSola@imb-mainz.de",
                                                                                                           subject = "Comments and bugs: RBP Interactome shiny app",
                                                                                                           text = "A.FraderaSola@imb-mainz.de"), style = "font-size:9pt;"),
                                           em("Last update: November 2023", style = "font-size:9pt;")))),
                  tabPanel(HTML("<i style=color:#00A651 >L. infatum</i>"),
                           fluidRow(column(2,
                                           h2("Settings"),
                                           selectInput(inputId = "infantum_ui_datasetID", label = h4("Select species:"), choices = c(paste0(unique(df_infantum$Species),collapse = " & "),
                                                                                                                                        unique(df_infantum$Species))),
                                           checkboxGroupInput(inputId = "infantum_ui_timepointID",
                                                              label = h4("Select infection time points:"),
                                                              choices = unique(df_infantum$TimePoint),
                                                              selected = unique(df_infantum$TimePoint))),
                                    column(6,
                                           h2("Quantified proteins"),
                                           h2(""),
                                           dataTableOutput("infantum_MainDataTable")),
                                    column(4,
                                           h2("Selected proteins:"),
                                           selectizeInput('infantum_ui_selectedIDs',
                                                          NULL,
                                                          choices=NULL,
                                                          multiple=TRUE),
                                           actionButton("update_infantum_MainDataTable",
                                                        "Update selection"))),
                           navbarPage("Proteome Analysis",
                                      tabPanel("Exploratory Analysis",
                                               fluidRow(column(6,
                                                               HTML("<h4><b>PCA plot</b></h4>"),
                                                               plotOutput("infantum_PCA",height = "1000px")),
                                                        column(6,
                                                               HTML("<h4><b>HeatMap plot</b></h4>"),
                                                               plotOutput("infantum_HeatMap",height = "1000px")))),
                                      tabPanel("Clustering analysis",
                                               fluidRow(
                                                 column(8,
                                                        HTML("<h4><b>Lineplot: Resulting clusters and their mean</b></h4>")),
                                                 column(4,
                                                        HTML("<h4><b>Barplot: Protein count per cluster</b></h4>"))
                                               ),
                                               fluidRow(
                                                 column(4,
                                                        bsCollapsePanel("Advanced settings",
                                                                        column(6,
                                                                               sliderInput("infantum_xDIM", "Select X dimensions:",
                                                                                           min = 1, max = 3, 
                                                                                           value = 2, step = 1)),
                                                                        column(6,
                                                                               sliderInput("infantum_yDIM", "Select Y dimensions:",
                                                                                           min = 1, max = 3,
                                                                                           value = 3, step = 1))))),
                                               fluidRow(column(8,
                                                               plotOutput("infantum_ClusterLinePlot",height = "1000px")),
                                                        column(4,
                                                               plotlyOutput("infantum_ClusterBarPlot",height = "1000px")))),
                                      tabPanel("Pairwise Analysis - Time course",
                                               fluidRow(column(6,
                                                               HTML("<h4><b>Boxplot: Proteome distribution along the time course</b></h4>"),
                                                               plotOutput("infantum_Boxplot",height = "1000px")),
                                                        column(6,
                                                               HTML("<h4><b>Dotplot: Selected ID statiscal significance</b></h4>"),
                                                               plotOutput("infantum_Dotplot",height = "1000px")))),
                                      tabPanel("Pairwise Analysis - Reference",
                                               fluidRow(column(12,
                                                               HTML("<h4><b>Volcano plot: Individual IDs fold change and p-value</b></h4>"))),
                                               fluidRow(column(2,
                                                               selectInput(inputId = "infantum_referenceTP", label = h4("Select a reference time point:"), choices = unique(df_infantum$TimePoint))),
                                                        column(2,
                                                               selectInput(inputId = "infantum_TP", label = h4("Select a time point:"), choices = unique(df_infantum$TimePoint))),
                                                        column(4,
                                                               bsCollapsePanel("Advanced settings",
                                                                               column(6,
                                                                                      selectInput(inputId = "infantum_Pvalue", label = h4("Select a p-value:"), choices = c(0.05,0.01))),
                                                                               column(6,
                                                                                      sliderInput("infantum_LFC", "Select a log2(FoldChange):",
                                                                                                  min = 0, max = 5,
                                                                                                  value = 1, step = 0.1))))),
                                               plotlyOutput("infantum_Volcanoplot",height = "1000px")))),
                  tabPanel(HTML("<i style=color:#EE2A7B >L. major</i>"),
                           fluidRow(column(2,
                                           h2("Settings"),
                                           selectInput(inputId = "major_ui_datasetID", label = h4("Select species:"), choices = c(paste0(unique(df_major$Species),collapse = " & "),
                                                                                                                                     unique(df_major$Species))),
                                           checkboxGroupInput(inputId = "major_ui_timepointID",
                                                              label = h4("Select infection time points:"),
                                                              choices = unique(df_major$TimePoint),
                                                              selected = unique(df_major$TimePoint))),
                                    column(6,
                                           h2("Quantified proteins"),
                                           h2(""),
                                           dataTableOutput("major_MainDataTable")),
                                    column(4,
                                           h2("Selected proteins:"),
                                           selectizeInput('major_ui_selectedIDs',
                                                          NULL,
                                                          choices=NULL,
                                                          multiple=TRUE),
                                           actionButton("update_major_MainDataTable",
                                                        "Update selection"))),
                           navbarPage("Proteome Analysis",
                                      tabPanel("Exploratory Analysis",
                                               fluidRow(column(6,
                                                               HTML("<h4><b>PCA plot</b></h4>"),
                                                               plotOutput("major_PCA",height = "1000px")),
                                                        column(6,
                                                               HTML("<h4><b>HeatMap plot</b></h4>"),
                                                               plotOutput("major_HeatMap",height = "1000px")))),
                                      tabPanel("Clustering analysis",
                                               fluidRow(
                                                 column(8,
                                                        HTML("<h4><b>Lineplot: Resulting clusters and their mean</b></h4>")),
                                                 column(4,
                                                        HTML("<h4><b>Barplot: Protein count per cluster</b></h4>"))
                                               ),
                                               fluidRow(
                                                 column(4,
                                                        bsCollapsePanel("Advanced settings",
                                                                        column(6,
                                                                               sliderInput("major_xDIM", "Select X dimensions:",
                                                                                           min = 1, max = 3, 
                                                                                           value = 2, step = 1)),
                                                                        column(6,
                                                                               sliderInput("major_yDIM", "Select Y dimensions:",
                                                                                           min = 1, max = 3,
                                                                                           value = 3, step = 1))))),
                                               fluidRow(column(8,
                                                               plotOutput("major_ClusterLinePlot",height = "1000px")),
                                                        column(4,
                                                               plotlyOutput("major_ClusterBarPlot",height = "1000px")))),
                                      tabPanel("Pairwise Analysis - Time course",
                                               fluidRow(column(6,
                                                               HTML("<h4><b>Boxplot: Proteome distribution along the time course</b></h4>"),
                                                               plotOutput("major_Boxplot",height = "1000px")),
                                                        column(6,
                                                               HTML("<h4><b>Dotplot: Selected ID statiscal significance</b></h4>"),
                                                               plotOutput("major_Dotplot",height = "1000px")))),
                                      tabPanel("Pairwise Analysis - Reference",
                                               fluidRow(column(12,
                                                               HTML("<h4><b>Volcano plot: Individual IDs fold change and p-value</b></h4>"))),
                                               fluidRow(column(2,
                                                               selectInput(inputId = "major_referenceTP", label = h4("Select a reference time point:"), choices = unique(df_major$TimePoint))),
                                                        column(2,
                                                               selectInput(inputId = "major_TP", label = h4("Select a time point:"), choices = unique(df_major$TimePoint))),
                                                        column(4,
                                                               bsCollapsePanel("Advanced settings",
                                                                               column(6,
                                                                                      selectInput(inputId = "major_Pvalue", label = h4("Select a p-value:"), choices = c(0.05,0.01))),
                                                                               column(6,
                                                                                      sliderInput("major_LFC", "Select a log2(FoldChange):",
                                                                                                  min = 0, max = 5,
                                                                                                  value = 1, step = 0.1))))),
                                               plotlyOutput("major_Volcanoplot",height = "1000px")))),
                  tabPanel(HTML("<i style=color:#2B3990 >L. mexicana</i>"),
                           fluidRow(column(2,
                                           h2("Settings"),
                                           selectInput(inputId = "mexicana_ui_datasetID", label = h4("Select species:"), choices = c(paste0(unique(df_mexicana$Species),collapse = " & "),
                                                                                                                                  unique(df_mexicana$Species))),
                                           checkboxGroupInput(inputId = "mexicana_ui_timepointID",
                                                              label = h4("Select infection time points:"),
                                                              choices = unique(df_mexicana$TimePoint),
                                                              selected = unique(df_mexicana$TimePoint))),
                                    column(6,
                                           h2("Quantified proteins"),
                                           h2(""),
                                           dataTableOutput("mexicana_MainDataTable")),
                                    column(4,
                                           h2("Selected proteins:"),
                                           selectizeInput('mexicana_ui_selectedIDs',
                                                          NULL,
                                                          choices=NULL,
                                                          multiple=TRUE),
                                           actionButton("update_mexicana_MainDataTable",
                                                        "Update selection"))),
                           navbarPage("Proteome Analysis",
                                      tabPanel("Exploratory Analysis",
                                               fluidRow(column(6,
                                                               HTML("<h4><b>PCA plot</b></h4>"),
                                                               plotOutput("mexicana_PCA",height = "1000px")),
                                                        column(6,
                                                               HTML("<h4><b>HeatMap plot</b></h4>"),
                                                               plotOutput("mexicana_HeatMap",height = "1000px")))),
                                      tabPanel("Clustering analysis",
                                               fluidRow(
                                                 column(8,
                                                        HTML("<h4><b>Lineplot: Resulting clusters and their mean</b></h4>")),
                                                 column(4,
                                                        HTML("<h4><b>Barplot: Protein count per cluster</b></h4>"))
                                               ),
                                               fluidRow(
                                                 column(4,
                                                        bsCollapsePanel("Advanced settings",
                                                                        column(6,
                                                                               sliderInput("mexicana_xDIM", "Select X dimensions:",
                                                                                           min = 1, max = 3, 
                                                                                           value = 2, step = 1)),
                                                                        column(6,
                                                                               sliderInput("mexicana_yDIM", "Select Y dimensions:",
                                                                                           min = 1, max = 3,
                                                                                           value = 3, step = 1))))),
                                               fluidRow(column(8,
                                                               plotOutput("mexicana_ClusterLinePlot",height = "1000px")),
                                                        column(4,
                                                               plotlyOutput("mexicana_ClusterBarPlot",height = "1000px")))),
                                      tabPanel("Pairwise Analysis - Time course",
                                               fluidRow(column(6,
                                                               HTML("<h4><b>Boxplot: Proteome distribution along the time course</b></h4>"),
                                                               plotOutput("mexicana_Boxplot",height = "1000px")),
                                                        column(6,
                                                               HTML("<h4><b>Dotplot: Selected ID statiscal significance</b></h4>"),
                                                               plotOutput("mexicana_Dotplot",height = "1000px")))),
                                      tabPanel("Pairwise Analysis - Reference",
                                               fluidRow(column(12,
                                                               HTML("<h4><b>Volcano plot: Individual IDs fold change and p-value</b></h4>"))),
                                               fluidRow(column(2,
                                                               selectInput(inputId = "mexicana_referenceTP", label = h4("Select a reference time point:"), choices = unique(df_mexicana$TimePoint))),
                                                        column(2,
                                                               selectInput(inputId = "mexicana_TP", label = h4("Select a time point:"), choices = unique(df_mexicana$TimePoint))),
                                                        column(4,
                                                               bsCollapsePanel("Advanced settings",
                                                                               column(6,
                                                                                      selectInput(inputId = "mexicana_Pvalue", label = h4("Select a p-value:"), choices = c(0.05,0.01))),
                                                                               column(6,
                                                                                      sliderInput("mexicana_LFC", "Select a log2(FoldChange):",
                                                                                                  min = 0, max = 5,
                                                                                                  value = 1, step = 0.1))))),
                                               plotlyOutput("mexicana_Volcanoplot",height = "1000px")))),
                  tabPanel("Orthology",
                           navbarPage("Orthology analysis",
                                      tabPanel("Proteinortho analysis",
                                               fluidRow(
                                                 column(12,
                                                        h2("Orthology table:"),
                                                        dataTableOutput("Ortho_table"))),
                                               fluidRow(
                                                 column(4,
                                                        h2("Selected orthology groups:"),
                                                        selectizeInput('ui_orthoSelectedIDs',
                                                                       NULL,
                                                                       choices=NULL,
                                                                       multiple=TRUE),
                                                        actionButton("update_ortho_MainDataTable",
                                                                     "Update selection"))),
                                               h4("Line plot: Expression mean at each time point"),
                                               plotOutput("OrthoPlot",height = "1000px"))))
                  )
